back/BMW/BMW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/BMW/goods/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:category_slug>/', views.CategoriesView.as_view(), name='categories'),
    path('goods/<slug:goods_slug>/', views.GoodsView.as_view(), name='goods')
]

back/BMW/main/urls.py
from django.contrib import admin
from django.urls import path, include


from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.main, name='main')
]

back/BMW/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
]

back/BMW/goods/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    image = models.ImageField(upload_to='category_images', blank=True, null=True, verbose_name='Изображение')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Goods(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    power = models.CharField(max_length=150, verbose_name='Мощность')
    acceleration = models.DecimalField(default=0.00, max_digits=3, decimal_places=2, verbose_name='Разгон')
    consumption = models.DecimalField(default=0.00, max_digits=3, decimal_places=2, verbose_name='Расход')
    emissions = models.IntegerField(verbose_name='Выбросы')
    category = models.ForeignKey(to=Categories, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'goods'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("id",)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('goods:product', kwargs={'product_slug': self.slug})

back/BMW/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

back/BMW/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class ProfileForm(UserChangeForm):
    pass


class UserRegistrationForm(UserCreationForm):
    pass

back/BMW/goods/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from goods.models import Categories, Goods


# Create your views here.

# class Catalog(ListView):
#     pass

def catalog(request):
    categorie = Categories.objects.all()

    context = {
        'categories': categorie,
    }
    return render(request, 'goods/catalog.html', context)


# def categories(request):
#     return render(request, 'goods/categories.html')

class CategoriesView(ListView):
    model = Goods
    template_name = "goods/categories.html"
    context_object_name = 'goods'
    allow_empty = False

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')

        if category_slug == "all":
            goodies = super().get_queryset()
        else:
            goodies = super().get_queryset().filter(category__slug=category_slug)
        return goodies

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Categories.objects.all()
        return context


class GoodsView(DetailView):
    template_name = "goods/goods.html"
    slug_url_kwarg = 'goods_slug'
    context_object_name = 'good'

    def get_object(self, queryset=None):
        good = Goods.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return good

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        return context


# def goods(request):
#     context = {
#         'goods': Goods.objects.all()
#     }
#     return render(request, 'goods/goods.html', context)

back/BMW/main/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'main/index.html')


def main(request):
    return render(request, 'main/main.html')

back/BMW/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.cache import cache

from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView

# from carts.models import Cart
# from common.mixins import CacheMixin
# from orders.models import Order, OrderItem
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    # success_url = reverse_lazy('main:index')

    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page and redirect_page != reverse('user:logout'):
            return redirect_page

        return reverse_lazy('main:main')

    def form_valid(self, form):
        session_key = self.request.session.session_key

        user = form.get_user()

        if user:
            auth.login(self.request, user)
            if session_key:
                messages.success(self.request, f'{user.username}, Вы вошли в аккаунт')
                return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context


class UserRegistrationView(CreateView):
    template_name = 'users/register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)

            messages.success(self.request, f'Все оке')
            return HttpResponseRedirect(self.get_success_url())


class UserProfileView(UpdateView):
    template_name = 'users/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')



@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

back/BMW/goods/templates/goods/catalog.html
{% extends 'base.html' %}
{% load static %}



    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/catalog.css' %}">
    {% endblock %}


    {% block content %}
    <p class="PageName">Каталог</p>
    <div class="categories">
        <div class="category">
            {% for category in categories %}
            <div class="catname">
                <a class="catname" href="{% url 'goods:categories' category.slug %}">{{ category.name }}</a>
            </div>
            <img class="imag" src="{{ category.image.url }} " alt="{{ category.slug }}">
            {% endfor %}
        </div>
    </div>
    {% endblock %}

back/BMW/goods/templates/goods/categories.html
{% extends 'base.html' %}
{% load static %}

    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/categories.css' %}">
    {% endblock %}


    {% block content %}
    <p class="PageName">{{ category.name }}</p>
    <div class="categories">
        {% for good in goods %}
        <img class="imag" src="{{ category.image.url }}" alt="{{ category.slug }}">
        <div class="category">
            <a class="catname" href="{% url 'goods:goods' good.slug %}">{{ good.name }}</a>
            <p class="price">{{ good.price }}</p>
            <p class="descr">{{ good.description }}</p>
        </div>
            {% endfor %}
    </div>
    {% endblock %}

back/BMW/goods/templates/goods/goods.html
{% extends 'base.html' %}
{% load static %}


    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/goods.css' %}">
    {% endblock %}



    {% block content %}
    <p class="PageName">{{ good.name }}</p>
    <img class="imag" src="{{ good.image.url }}" alt="m5">
    <div class="main">
        <p class="name">{{ good.name }}</p>
        <p class="price">{{ good.price }}</p>
        <p class="descr">{{ good.description }}</p>
    </div>
    <div class="param">
        <ul class="pname">
            <li><p>Мощность, кВт (л.с.) при об/мин:</p></li>
            <li><p>Разгон 0–100 км/ч в секундах:</p></li>
            <li><p>Расход топлива в смешанном цикле, л/100 км:</p></li>
            <li><p>Выбросы CO2 в г/км (смешанный цикл):</p></li>
        </ul>
        <ul class="pvalue">
            <li><p>{{ good.power }}</p></li>
            <li><p>{{ good.acceleration }}</p></li>
            <li><p>{{ good.consumption }}</p></li>
            <li><p>{{ good.emissions }}</p></li>
        </ul>
    </div>
    <a class="zak" href="#">Получить предложение</a>
    {% endblock %}

back/BMW/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMW</title>
    <link rel="stylesheet" href= {% static '/styles/index.css' %}>
    <link rel="icon" type="images/x-icon" href="./Фавикон/new logo 3 (1).ico">
    
</head>
<body background="{% static 'static/headLights2.png' %}">
    <img class="logo" src={% static 'static\logo.png' %} alt="logo">
    <p class="slogan">Freude am Fahren</p>
    <a class="text" href="{% url 'main:main' %}" target="_blank">BMW</a>
</body>
</html>

back/BMW/main/templates/main/main.html
{% extends 'base.html' %}
{% load static %}

    {% block css %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock %}

    {% block content %}
    <p class="nadpis">Bayerische Motoren Werke AG</p>
    
    <span class="descr">
        <p class="innerDescr">BMW - уже не просто автомобиль.</p>
        <p class="innerDescr">Это качество и уровень, созданный многолетней историей и доказанный на практике.</p>
        <p class="innerDescr">С BMW не бывает плохих дней.</p>
    </span>
    <img class="m5" src="{% static 'static\bmwM5.jpg' %}" alt="bmwM5">


    <p class="spec">Специальное предложение</p>

    <img class="specImg" src="{% static 'static\m5-1.png' %}" alt="m5-1">
    <p class="name">BMW 520i седан</p>
    <p class="price">$35 000</p>
    <a class="more" href="#">Узнать больше</a>

    <span>
        <p class="catalog">Каталог</p>

        <img class="specImg1" src="{% static 'static\bmw-new-x7.png' %}" alt="m5-1">
        <p class="name1">BMW X7 2023</p>
        <p class="price1">$75 000</p>
        <a class="more1" href="#">Узнать больше</a>
    <!--
        <img class="specImg2" src="static\bmw-x3.png" alt="m5-1">
        <p class="name2">BMW X3 2023</p>
        <p class="price2">$60 000</p>
        <a class="more2" href="#">Узнать больше</a> -->
    </span>

    <p class="catlink">
        <a class="catlink" href="{% url 'goods:catalog' %}">Перейти к каталогу ></a>
    </p>


    <p class="subscription">Подписка на BMW</p>
    <img class="wha" src="{% static 'static\amobil.webp' %}" alt="wha?">
    <p class="supsubb">
        <p class="subb">Возможность пользования </p>
        <p class="subb">автомобилем без необходимости</p>
        <p class="subb">покупки</p>
        <a class="subbl" href="#">Узнать больше</a>
    </p>


    {% endblock %}

back/BMW/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMW</title>

    {% block css %}
    {% endblock %}

    <link rel="icon" type="images/x-icon" href="./Фавикон/new logo 3 (1).ico">

</head>
<body>
    <a href="{% url 'main:main' %}"><img class="logo" src="{% static 'static\logo.png' %}" alt="logo"></a>

    <div id="header" class="header">
        <ul>
            <li><a href="{% url 'goods:catalog' %}" target="_blank">Каталог</a></li>
            <li><a href="#">Личный кабинет</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">Корзина</a></li>
        </ul>
    </div>


    {% block content %}
    {% endblock %}


<div class="footer">
    <p class="s">© BMW AG 2024</p>
</div>

</body>
</html>

back/BMW/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMW</title>
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="icon" type="images/x-icon" href="./Фавикон/new logo 3 (1).ico">

</head>
<body>
    <img class="logo" src="{% static 'static\logo.png'%}" alt="logo">
    
    <div id="header" class="header">
        <ul>
            <li><a href="#">Каталог</a></li>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">Корзина</a></li>
        </ul>
    </div>

    <div class="cont">
        <p class=log>Войти</p>
        <form class="form" action="{% url "user:login" %}" method="post">
            {% csrf_token %}
            Логин <input type="text" name="login" size="10">
            Пароль <input type="password" name="password" size="10">
        </form>
    </div>

    <div class="footer">
        <p class="s">© BMW AG 2024</p>
    </div>
</body>
</html>

back/BMW/users/templates/users/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMW</title>
    <link rel="stylesheet" href="{% static 'styles/cabinet.css' %}">
    <link rel="icon" type="images/x-icon" href="./Фавикон/new logo 3 (1).ico">

</head>
<body>
    <img class="logo" src="{% static 'static\logo.png' %}" alt="logo">
    
    <div id="header" class="header">
        <ul>
            <li><a href="#">Каталог</a></li>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">Корзина</a></li>
        </ul>
    </div>

    <div class="info">
        <p class="priv">Здравстуйте, Matt!</p>
        <img src="{% static 'static\profile.png'%} " alt="profile pic" width="150px" height="auto">
        <p class="name">Matt</p>
        <p class="email">email@gmail.com</p>
        <p class="birth">23.02.2003</p>
        <p class="rang">Silver</p>
    </div>

    <div class="prev">
        <p class="prevname">Предыдущие покупки</p>
        <ul class="prevlist">
            <li>BMW m5</li>
        </ul>
    </div>

    <div class="footer">
        <p class="s">© BMW AG 2024</p>
    </div>
</body>
</html>

back/BMW/users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMW</title>
    <link rel="stylesheet" href="{% static 'styles/register.css' %}">
    <link rel="icon" type="images/x-icon" href="./Фавикон/new logo 3 (1).ico">

</head>
<body>
    <img class="logo" src="{% static 'static\logo.png' %}" alt="logo">
    
    <div id="header" class="header">
        <ul>
            <li><a href="#">Каталог</a></li>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">Корзина</a></li>
        </ul>
    </div>

    <div class="cont">
        <p class=log>Зарегистрироваться</p>
        <form class="form" action="#" method="post">
            Имя <input type="text" name="fio">
            Логин <input type="text" name="login" size="10">
            Пароль <input type="password" name="password" size="10">
            email <input type="email" name="email">
        </form>
    </div>

    <div class="footer">
        <p class="s">© BMW AG 2024</p>
    </div>
</body>
</html>